### ISSUE TITLE
Getting token

### ISSUE THREAD

**Issue by dontbanmeplz** [velut/verify-hcaptcha#70]
Do you know of a way to get the token after someone solves a captcha? I would like to use this project, thanks

**Comment by velut** [comment]
Hi @dontbanmeplz, thanks for your interest in the project.

After a user solves a challenge on the client, the hCaptcha API returns a token. You can then send the token to your server and use this library to verify that it is valid.

See the official docs at https://docs.hcaptcha.com/.

**Comment by dontbanmeplz** [comment]
how can i get that token? I have read through the docs and cant find it

**Comment by velut** [comment]
You need to use the official hCaptcha script on your website and configure it.

Quoting from https://docs.hcaptcha.com/#add-the-hcaptcha-widget-to-your-webpage:

> Typically, you'll want to include the empty .h-captcha container inside an HTML form. When a captcha is successfully solved, a hidden token will automatically be added to your form that you can then POST to your server for verification. You can retrieve it server side with POST parameter h-captcha-response.

Quoting from https://docs.hcaptcha.com/configuration#hcaptcha-container-configuration:
> The second way to configure hCaptcha is to set custom attributes on the hCaptcha container `<div>`. You're already required to do this with data-sitekey, but there are a handful of other optional attributes that enable more customization.

Attribute | Value | Description
-- | -- | --
data-callback | function name | Optional. Called when the user submits a successful response. The h-captcha-response token is passed to your callback.

Note that this library has to run on the server and can only verify tokens, getting them is out of scope.

**Comment by dontbanmeplz** [comment]
Perfect thanks so much
